# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Enrique Comba Riepenhausen
tagline:          ''
description:      'I am a <a href="http://en.wikipedia.org/wiki/The_Fool_(Tarot_card)" target="_blank">fool</a>, <a href="http://www.philoscifi.com/love-of-wisdom" target="_blank">philosopher</a>, <a href="http://manifesto.softwarecraftsmanship.org" target="_blank">software craftsman</a>, <a href="https://github.com/ecomba" target="_blank">maker</a> of things in search of <a href="/images/wisdom.jpg" target="_blank">wisdom</a> and enlightenment.'
url:              http://ecomba.pro

author:
  name:           'Enrique Comba Riepenhausen'
  url:            https://ecomba.pro

paginate:         10

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ecomba
