# Site settings
title:          Enrique's Musings
description:    "Where I ponder about matters that pop into my headspace"
baseurl:        ""
url:            "https://blog.ecomba.pro"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Enrique Comba Riepenhausen
  url:          https://ecomba.pro
  email:        hello@ecomba.pro

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale