# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Enrique Comba Riepenhausen
tagline:          'Thoughts of a restless mind'
description:      'I am a restless <a href="http://en.wikipedia.org/wiki/The_Fool_(Tarot_card)" target="_blank">fool</a>, <a href="http://www.philoscifi.com/love-of-wisdom" target="_blank">philosopher</a>, <a href="http://manifesto.softwarecraftsmanship.org" target="_blank">software craftsman</a>, <a href="http://makersacademy.com" target="_blank">maker of makers</a> in search of wisdom and enlightenment.'
url:              http://ecomba.pro

author:
  name:           'Enrique Comba Riepenhausen'
  url:            https://twitter.com/ecomba

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ecomba
