# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Enrique Comba Riepenhausen
tagline:          'Thoughts of a restless mind'
description:      ''
url:              http://ecomba.pro

author:
  name:           'Enrique Comba Riepenhausen'
  url:            https://twitter.com/ecomba

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ecomba
